name: mayuripaliwal
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  lottie: ^2.7.0
  flutter:
    sdk: flutter
  sqflite: ^2.4.0
  path: ^1.9.1
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.11.0
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/mobilebert.tflite
    - assets/vocab.txt
    - assets/labels.txt
    - assets/register.jpg
    - assets/google_logo.png
    - assets/apple_logo.png
    - assets/facebook_logo.png
    - assets/empty.json
